import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { fillDefaults } from '../src/cloud/playerModel.js';
import { verifyCombat } from '../src/cloud/combatVerify.js';
import { playBot } from './helpers/combat-bot.mjs';
import { ADMIN_CHECKPOINTS } from '../src/admin/config.js';
import { WORLD,INTERACTIVES,ENEMY_SPAWNS } from '../src/config/world.layout.js';
import { buildNav } from '../src/world/nav.js';
import { buildTerrain } from '../src/world/terrain.js';
import { collectSolids } from '../src/world/solids.js';
import { PROPS,resolveMap } from '../src/world/mapData.js';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
const users = {}, ids = {}; let checks=0;
const sql=(s,p=[])=>db.query(s,p);
async function as(n,fn) { await db.exec('set role authenticated'); await sql("select set_config('request.jwt.claim.sub',$1,false)",[users[n]]);try{return await fn();}finally{await db.exec('reset role');} }
const call=(n,op,args={},id=null)=>as(n,async()=>(await sql('select public.admin_request($1,$2::jsonb,$3::uuid) j',[op,JSON.stringify(args),id])).rows[0].j);
const check=(v,label)=>{assert.ok(v,label);checks++;console.log('  ✓',label);};
const migrate=()=>db.exec(readFileSync('supabase/migrations/20261008_test_admin.sql','utf8'));
async function change(n,target,op,args={},id=randomUUID()) { const p=await call(n,'player',{playerId:ids[target]}); return call(n,op,{playerId:ids[target],revision:p.revision,walletRevision:p.walletRevision,...args},id); }
try {
  for (const f of ['tools/sql/auth-stub.sql','supabase/schema.sql','supabase/migrations/20261004_game_chat.sql','supabase/migrations/20261004_chat_roles_v2.sql','supabase/migrations/20261005_chat_amulet_catalog.sql','supabase/migrations/20261006_chat_catalog_ch2.sql','supabase/migrations/20261007_covens.sql','supabase/migrations/20261008_coven_cycles.sql']) await db.exec(readFileSync(f,'utf8'));
  for(const n of ['player','support','developer','admin','owner']) { users[n]=randomUUID();await sql('insert into auth.users(id) values($1)',[users[n]]);await as(n,()=>sql("select public.create_player('witch')"));await sql('select public.claim_nickname($1,$2,$2)',[users[n],n]);if(n!=='player') await sql('insert into game_chat.roles(user_id,roles) values($1,$2)',[users[n],[n]]);ids[n]=String((await sql('select player_id from public.profiles where id=$1',[users[n]])).rows[0].player_id); }
  await sql("select public.admin_grant_sapphires($1,200,'Before install','old-test')",[users.owner]);
  await migrate(); const count=(await sql('select count(*) n from game_admin.entries')).rows[0].n;await migrate();check((await sql('select count(*) n from game_admin.entries')).rows[0].n===count,'migration repeat preserves baselines and history');
  check((await call('owner','bootstrap')).me.role==='owner','real role and catalog bootstrap');
  await assert.rejects(()=>call('player','bootstrap'),/admin_forbidden/);
  const result=await change('owner','owner','resources',{changes:[{item:'sapphires',delta:50},{item:'coins',delta:500},{item:'moon_herb',delta:110}],reason:''});
  check(result.player.snapshot.wallet.sapphires===250 && result.player.snapshot.inventory.coins>=500,'owner grants currencies to self with empty reason');
  const bag=result.player.snapshot.objects.player_bag;check(result.player.bagUsed===bag.capacity && bag.pending.moon_herb>0,'overflow grants fill space and preserve remainder pending');
  const op=await call('owner','operation',{operation:result.operation});check(op.entries.length===4 && op.reason===null,'one operation has wallet, bag and pending rows, optional reason');
  const p=await call('owner','player',{playerId:ids.owner}),rid=randomUUID(),args={playerId:ids.owner,revision:p.revision,walletRevision:p.walletRevision,changes:[{item:'coins',delta:1}]};
  await call('owner','resources',args,rid);check((await call('owner','resources',args,rid)).repeated,'retry applies exactly once');
  await assert.rejects(()=>call('owner','resources',{...args,changes:[{item:'coins',delta:2}]},rid),/admin_request_reused/);
  await assert.rejects(()=>call('owner','resources',args,randomUUID()),/admin_conflict/);
  await assert.rejects(()=>change('developer','developer','resources',{changes:[{item:'coins',delta:1}]}),/admin_forbidden/);
  await assert.rejects(()=>change('developer','owner','resources',{changes:[{item:'coins',delta:1}]}),/admin_forbidden/);
  await assert.rejects(()=>change('developer','player','resources',{changes:[{item:'sapphires',delta:1}]}),/admin_forbidden/);
  await assert.rejects(()=>change('support','player','resources',{changes:[{item:'coins',delta:1}]}),/admin_forbidden/);
  await assert.rejects(()=>change('owner','owner','resources',{changes:[{item:'coins',delta:10},{item:'nonsense',delta:1}]}),/admin_invalid/);
  const cur=await call('owner','player',{playerId:ids.owner});check(cur.snapshot.inventory.coins===p.snapshot.inventory.coins+1,'failed batch rolls back all changes');
  await change('owner','owner','resources',{changes:[{item:'moon_herb',delta:-1,storage:'pending'}]});
  await assert.rejects(()=>change('owner','owner','help',{command:'repair_gift',ability:'ice'}),/admin_no_proof/);
  await sql("insert into public.player_quests(user_id,quest_id) values($1,'unlock_ice_1')",[users.owner]);
  const fixed=await change('owner','owner','help',{command:'repair_gift',ability:'ice'});check(fixed.player.snapshot.abilities.ice.level===1,'gift repair requires confirmed quest proof');
  await change('owner','owner','restore',{operation:fixed.operation});check(!(await call('owner','player',{playerId:ids.owner})).snapshot.abilities.ice?.unlocked,'safe restore reverses recorded gift repair');
  await assert.rejects(()=>change('owner','owner','restore',{operation:fixed.operation}),/admin_not_restorable/);
  await assert.rejects(()=>change('owner','owner','help',{command:'teleport',checkpoint:'city'}),/admin_checkpoint_locked/);
  const moved=await change('owner','owner','help',{command:'teleport',checkpoint:'forest'});
  const sync=await as('owner',async()=>(await sql("select public.sync_player($1::jsonb) j",[JSON.stringify({id:randomUUID(),supportRevision:'0',pos:{x:2,y:2},safe:{x:2,y:2}})])).rows[0].j);
  check(sync.pos.x===moved.player.snapshot.pos.x,'stale game save cannot overwrite admin teleport');
  await assert.rejects(()=>change('owner','owner','restore',{operation:moved.operation}),/admin_restore_conflict/);
  // Gameplay must keep its atomic ledger grouping; the browser never supplies balances.
  const act=(op,extra={})=>as('player',async()=>(await sql('select public.player_action($1::jsonb) j',[JSON.stringify({op,id:randomUUID(),...extra})])).rows[0].j);
  await change('owner','player','resources',{changes:[{item:'coins',delta:500},{item:'moon_herb',delta:20},{item:'forest_mushroom',delta:10}]});
  await sql("select public._add_event($1,'city_merchant_open')",[users.player]);
  const sold=await act('shop_sell',{item:'moon_herb',qty:10});check(sold.action.ok,'shop sale still executes through wrapped gameplay');
  const sale=(await call('owner','ledger',{playerId:ids.player,source:'trade'})).rows;
  check(sale.length===2 && sale[0].operation===sale[1].operation && sale.some(r=>r.resource==='coins'&&r.delta===50)&&sale.some(r=>r.resource==='moon_herb'&&r.delta===-10),'sale links item withdrawal and coin income under one operation');
  const gathered=await act('world',{obj:'herb_g1'});check(gathered.action.ok&&(await call('owner','ledger',{playerId:ids.player,source:'gather'})).rows.length===1,'ordinary gathering classified and audited');
  const crafted=await act('craft',{recipe:'elixir_life'});check(crafted.action.ok&&(await call('owner','ledger',{playerId:ids.player,source:'craft'})).rows.some(r=>r.resource==='elixir_life'&&r.delta>0),'crafting records ingredients and product');
  await sql("select public._unlock_ability($1,'telekinesis',1)",[users.player]);
  const begun=await act('combat_start',{spawn:'scavenger_01',enemy:'forest_scavenger',balanceVersion:30});check(begun.action.ok,'combat still starts after administration installed');
  const snap=(await sql('select public.combat_load($1) j',[users.player])).rows[0].j;
  const play=playBot(snap.combatCtx,{seed:41}),verdict=verifyCombat(fillDefaults(snap).snapshot,play.log,snap.combatSince+play.log.ticks/60*1000+2000);
  check(verdict.ok,'real combat replay verified');
  const ended=(await sql('select public.combat_apply($1,$2::jsonb) j',[users.player,JSON.stringify(verdict.verdict)])).rows[0].j;
  check(ended.action.ok && (await call('owner','stats')).combats.length===1,'combat apply and confirmed fight statistics survive wrapper');
  await sql('update public.player_progress set research=$2::jsonb where user_id=$1',[users.player,JSON.stringify({upgradeId:'telekinesis_2',startedAt:Date.now()})]);
  const research=await change('owner','player','help',{command:'finish_research'});check(research.player.snapshot.abilities.telekinesis.level===2&&research.player.snapshot.quests.includes('telekinesis_2_complete'),'support finishes only the existing research and records its completion');
  await change('owner','player','restore',{operation:research.operation});check((await call('owner','player',{playerId:ids.player})).snapshot.abilities.telekinesis.level===1,'research restoration reverses gift and newly completed event');
  const refreshed=await call('owner','player',{playerId:ids.player});
  const legacy=await as('owner',async()=>(await sql("select public.chat_request('resources',$1::jsonb,$2::uuid) j",[JSON.stringify({playerId:ids.player,revision:refreshed.revision,item:'coins',delta:5,reason:''}),randomUUID()])).rows[0].j);
  check(legacy.inventory.coins===refreshed.snapshot.inventory.coins+5,'existing chat grants use new server path and allow empty reason');
  await as('owner',()=>sql("select public.reset_player('witch')"));
  check((await call('owner','player',{playerId:ids.owner})).earnedGifts.ice===0,'new-game reset prevents gift proof from a previous playthrough');
  const map=resolveMap({storage:null,useDraft:false}),terrain=buildTerrain({ROADS:map.roads,WATERS:map.waters});
  const grid=buildNav({width:WORLD.width,height:WORLD.height,solids:collectSolids({colliders:map.colliders,props:PROPS,interactives:INTERACTIVES,enemies:ENEMY_SPAWNS,waterRects:terrain.waterRects,skip:new Set()})});
  check(Object.values(ADMIN_CHECKPOINTS).every(p=>grid.blocked[Math.round(p.y/grid.cell)*grid.cols+Math.round(p.x/grid.cell)]===0),'all server checkpoints are outside map collisions');
  // Reapply the canonical schema and administration: private cores refresh to the latest game implementation.
  const logged=(await sql('select count(*) n from game_admin.entries')).rows[0].n;
  await db.exec(readFileSync('supabase/schema.sql','utf8'));await migrate();
  check((await sql('select count(*) n from game_admin.entries')).rows[0].n===logged,'canonical schema plus migration retains existing history');
  const rulesBefore=(await sql("select value from game_admin.settings where key='rules'")).rows[0].value;
  const progressBefore=(await sql('select to_jsonb(p) row from public.player_progress p order by user_id')).rows;
  const legacyPoints=structuredClone(rulesBefore.checkpoints);
  Object.assign(legacyPoints.city,{x:6160,y:3110});Object.assign(legacyPoints.nerys,{x:8300,y:1960});Object.assign(legacyPoints.nerys_final,{x:7570,y:4160});
  await sql("update game_admin.settings set value=jsonb_set(value,'{checkpoints}',$1::jsonb) where key='rules'",[JSON.stringify(legacyPoints)]);
  const cityUpgrade=readFileSync('supabase/migrations/20261010_compact_city_admin_points.sql','utf8');
  const walkUpgrade=readFileSync('supabase/migrations/20261011_walkable_city_admin_points.sql','utf8');
  // Installations apply both city upgrades in order; repeating either keeps the final walkable-town points.
  await db.exec(cityUpgrade);await db.exec(walkUpgrade);await db.exec(walkUpgrade);
  assert.deepEqual((await sql("select value from game_admin.settings where key='rules'")).rows[0].value,rulesBefore);
  check(true,'city upgrades are repeatable, end at the walkable-town points and preserve gates and other admin rules');
  assert.deepEqual((await sql('select to_jsonb(p) row from public.player_progress p order by user_id')).rows,progressBefore);
  check((await sql('select count(*) n from game_admin.entries')).rows[0].n===logged,'city destination upgrade preserves player progress and audit history');
  for(const op of ['players','ledger','audit','errors','stats']) check(await call('support',op),`real ${op} query`);
  await assert.rejects(()=>as('owner',()=>sql('select * from game_admin.entries')),/permission denied/);
  await assert.rejects(()=>as('owner',()=>sql('select game_admin.core_player_action(\'{}\'::jsonb)')),/permission denied/);
  await assert.rejects(()=>as('owner',()=>sql("select public.combat_apply($1,'{}')",[users.owner])),/permission denied/);
  check(true,'private tables, copied cores and service combat inaccessible even to owner browser');
  console.log(`Admin DB: ${checks} checks passed`);
} catch(e) { console.error(e.message, e.detail || '', e.where || '',e.position,e.internalPosition,e.internalQuery);process.exitCode=1; } finally { await db.close(); }
