"""Export image-generated interior art: alpha trim, uniform resize, atomic WebP.

python3 tools/art/city-interiors.py /absolute/path/sources.json
Input: {asset_id: {path, prompt, editPrompt?}}. No creative image edits.
"""
import hashlib
import io
import json
from pathlib import Path
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'public/assets/city-interiors'
BOUNDS = {
    'bank_counter': (240, 132), 'bank_safe': (85, 138),
    'archive_shelf': (150, 155), 'archive_desk': (175, 110),
    'society_workbench': (190, 130), 'coven_cabinet': (130, 155),
    'coven_table': (175, 100), 'duel_rack': (90, 145),
}


def export(source, destination):
    payload = io.BytesIO()
    source.save(payload, format='WEBP', quality=88, method=6)
    data = payload.getvalue()
    assert len(data) > 100, destination
    with Image.open(io.BytesIO(data)) as check:
        check.load()
        assert check.size == source.size, destination
    staging = destination.with_suffix('.webp.part')
    staging.write_bytes(data)
    staging.replace(destination)


def main():
    sources = json.loads(Path(sys.argv[1]).read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    files, sizes, provenance = {}, {}, {}
    for asset_id, spec in sources.items():
        raw = Path(spec['path']).read_bytes()
        im = Image.open(io.BytesIO(raw))
        im.load()
        if asset_id == 'stone_floor':
            im = im.convert('RGB').resize((512, 512), Image.Resampling.LANCZOS)
        else:
            assert im.mode == 'RGBA', f'{asset_id}: requires genuine alpha'
            alpha = im.getchannel('A')
            assert alpha.getextrema()[0] == 0, f'{asset_id}: missing transparency'
            # Ignore nearly invisible edge specks only when measuring the canvas.
            box = alpha.point(lambda a: 255 if a > 8 else 0).getbbox()
            im = im.crop(box)
            bw, bh = BOUNDS[asset_id]
            factor = min(bw / im.width, bh / im.height)
            sizes['city_' + asset_id] = [round(im.width * factor), round(im.height * factor)]
            im.thumbnail((512, 512), Image.Resampling.LANCZOS)
        destination = OUT / (asset_id + '.webp')
        export(im, destination)
        files['city_' + asset_id] = 'assets/city-interiors/' + destination.name
        provenance[asset_id] = {
            'sha256': hashlib.sha256(raw).hexdigest(),
            'source': Path(spec['path']).name, 'generation': 'built-in imagegen',
            'prompt': spec['prompt'],
            **({'editPrompt': spec['editPrompt']} if spec.get('editPrompt') else {}),
        }
    # Small world manuscripts; UI icons keep their own independent sizing.
    sizes.update(city_archive_document=[45, 38], city_lab_journal=[45, 38], city_letters=[40, 32])
    (ROOT / 'src/config/city.interiors.generated.js').write_text(
        '// Generated by tools/art/city-interiors.py. Bottom-centre furniture pivots.\n'
        + 'export const CITY_INTERIOR_FILES = ' + json.dumps(files, indent=2) + ';\n'
        + 'export const CITY_INTERIOR_SIZES = ' + json.dumps(sizes, indent=2) + ';\n')
    (OUT / 'sources.json').write_text(json.dumps(provenance, indent=2) + '\n')
    print('Exported', len(files), 'interior assets.')


if __name__ == '__main__':
    main()
