// Approved multicolored witch town; generated by tools/art/prepare-witch-city.mjs.
export const CITY_WITCH_ATLASES = {
  "city_witch_north": "assets/city-witch/facades-north-v1.webp",
  "city_witch_south": "assets/city-witch/facades-south-v1.webp"
};
export const CITY_WITCH_SPRITES = {
  "city_final_north_bay_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 32,
      "y": 80,
      "w": 453,
      "h": 385
    },
    "anchor": {
      "x": 0.47902869757174393,
      "y": 0.9714285714285714
    }
  },
  "city_final_north_workshop_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 536,
      "y": 51,
      "w": 504,
      "h": 410
    },
    "anchor": {
      "x": 0.4365079365079365,
      "y": 0.9853658536585366
    }
  },
  "city_final_cellar_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 1053,
      "y": 56,
      "w": 458,
      "h": 411
    },
    "anchor": {
      "x": 0.5218340611353712,
      "y": 0.9878345498783455
    }
  },
  "city_final_rescue_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 34,
      "y": 527,
      "w": 467,
      "h": 408
    },
    "anchor": {
      "x": 0.4539614561027837,
      "y": 0.9828431372549019
    }
  },
  "city_final_archive_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 523,
      "y": 528,
      "w": 473,
      "h": 406
    },
    "anchor": {
      "x": 0.492600422832981,
      "y": 0.9876847290640394
    }
  },
  "city_final_society_exterior": {
    "atlas": "city_witch_north",
    "frame": {
      "x": 1031,
      "y": 516,
      "w": 483,
      "h": 416
    },
    "anchor": {
      "x": 0.4492753623188406,
      "y": 0.9903846153846154
    }
  },
  "city_final_bank_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 13,
      "y": 77,
      "w": 490,
      "h": 418
    },
    "anchor": {
      "x": 0.5551020408163265,
      "y": 0.992822966507177
    }
  },
  "city_final_duel_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 513,
      "y": 88,
      "w": 473,
      "h": 407
    },
    "anchor": {
      "x": 0.5369978858350951,
      "y": 0.9926289926289926
    }
  },
  "city_final_coven_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 1036,
      "y": 99,
      "w": 488,
      "h": 396
    },
    "anchor": {
      "x": 0.5491803278688525,
      "y": 0.9924242424242424
    }
  },
  "city_final_warehouse_a_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 23,
      "y": 602,
      "w": 504,
      "h": 349
    },
    "anchor": {
      "x": 0.4861111111111111,
      "y": 0.994269340974212
    }
  },
  "city_final_warehouse_b_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 565,
      "y": 619,
      "w": 510,
      "h": 335
    },
    "anchor": {
      "x": 0.49019607843137253,
      "y": 0.991044776119403
    }
  },
  "city_final_lab_exterior": {
    "atlas": "city_witch_south",
    "frame": {
      "x": 1109,
      "y": 587,
      "w": 396,
      "h": 376
    },
    "anchor": {
      "x": 0.39141414141414144,
      "y": 0.9680851063829787
    }
  }
};
